services:
  webserver:
    image: nginx:alpine
    container_name: web_server  # Custom container name :cite[1]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/usr/share/nginx/html  # Mount current folder as web root
      - ./logs:/var/log/nginx  # Log volume :cite[5]
    restart: unless-stopped
    